
image:
  file: .gitpod.Dockerfile

tasks:
  - init: mvn -N io.takari:maven:0.7.7:wrapper -Dmaven=3.8.0
      git config pull.rebase false

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - vscjava.vscode-maven

prebuild:
  - echo "default-java-version=11" >> ~/.gitpod.d/init.sh
